CREATE TABLE TEACH (
 id INTEGER NOT NULL AUTO_INCREMENT,
 name VARCHAR(20) NOT NULL,
 age NUMERIC(3) NOT NULL, --NUMERIC(3) means INTEGER
 nationality VARCHAR(2) NOT NULL,
 membership VARCHAR(1) NOT NULL,
 PRIMARY KEY(id),
 FOREIGN KEY (nationality)REFERENCES NATIONALITY (COUNTRY_CODE),
 FOREIGN KEY (membership)REFERENCES MEMBERSHIP (MEMBERSHIP_CODE)
);

--Step 1
CREATE TABLE NATIONALITY (
  
)