CREATE DATABASE SQL_EXERCISE4;

USE SQL_EXERCISE4;


CREATE TABLE PLAYERS(
PLAYER_ID INTEGER NOT NULL UNIQUE,
GROUP_ID INTEGER NOT NULL
);

INSERT INTO PLAYERS VALUES
(20, 2),
(30, 1),
(40, 3),
(45, 1),
(50, 2),
(65, 1);

CREATE TABLE MATCHES(
MATCH_ID INTEGER NOT NULL UNIQUE,
FIRST_PLAYER INTEGER NOT NULL,
SECOND_PLAYER INTEGER NOT NULL,
FIRST_SCORE INTEGER NOT NULL,
SECOND_SCORE INTEGER NOT NULL
);
insert into matches values (1, 30, 45, 10, 12);
insert into matches values (2, 20, 50, 5, 5);
insert into matches values (13, 65, 45, 10, 10);
insert into matches values (5, 30, 65, 3, 15);
insert into matches values (42, 45, 65, 8, 4);

SELECT * FROM PLAYERS;
SELECT * FROM MATCHES;

SELECT * FROM
PLAYERS P
LEFT JOIN MATCHES M
ON P.PLAYER_ID = M.FIRST_PLAYER;
-- AND P.PLAYER_ID = M.SECOND_PLAYER;

WITH TEMP AS (
SELECT FIRST_PLAYER AS PLAYER_ID ,FIRST_SCORE AS SCORE
FROM MATCHES
UNION
SELECT SECOND_PLAYER,SECOND_SCORE
FROM MATCHES),


TEMP2 AS (SELECT PLAYER_ID,SUM(SCORE) as TOTAL_SCORE
FROM TEMP
GROUP BY PLAYER_ID),


TEMP3 AS(
SELECT 
P.PLAYER_ID, T2.TOTAL_SCORE, P.GROUP_ID,
ROW_NUMBER() OVER ( PARTITION BY P.GROUP_ID ORDER BY T2.TOTAL_SCORE DESC ) AS RANKING
FROM PLAYERS P 
LEFT JOIN TEMP2 T2
ON T2.PLAYER_ID = P.PLAYER_ID
ORDER BY GROUP_ID ASC, TOTAL_SCORE DESC, PLAYER_ID ASC)

SELECT * FROM PLAYERS P
WHERE P.PLAYER_ID IN (SELECT PLAYER_ID FROM TEMP2);

SELECT PLAYER_ID AS WINNER_ID, GROUP_ID
FROM TEMP3
WHERE RANKING = 1;









